# Generated by Django 5.1.5 on 2025-02-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_supplier_price_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories_image/', verbose_name='Картинка товара'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='price_list',
            field=models.FileField(blank=True, null=True, upload_to='price_lists/', verbose_name='Прайс-лист (Excel)'),
        ),
    ]
