# Generated by Django 5.1.5 on 2025-02-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight_unit',
        ),
        migrations.AddField(
            model_name='product',
            name='compound',
            field=models.TextField(default=None, verbose_name='Состав'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='variety',
            field=models.CharField(default=None, max_length=10, verbose_name='Сорт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='image',
            field=models.CharField(max_length=200, null=True, verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(max_length=200, null=True, verbose_name='Картинка товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=200, null=True, verbose_name='Картинка товара'),
        ),
    ]
