# Generated by Django 5.1.5 on 2025-04-30 12:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight_unit',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='price_list',
        ),
        migrations.AddField(
            model_name='product',
            name='compound',
            field=models.CharField(default='default value', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='variety',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000, verbose_name='Сорт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Картинка товара'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Картинка товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='implementation_period',
            field=models.CharField(max_length=1000, verbose_name='Срок реализации'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='price_lists/', verbose_name='Прайс-лист №...')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricelists', to='products.supplier')),
            ],
        ),
    ]
