# Generated by Django 5.1.5 on 2025-02-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_weight_unit_product_compound_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Картинка товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Картинка товара'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Картинка'),
        ),
    ]
