# Generated by Django 5.1.5 on 2025-02-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='implementation_period',
            field=models.CharField(max_length=1000, verbose_name='Срок реализации'),
        ),
    ]
