# Generated by Django 5.1.5 on 2025-02-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_implementation_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variety',
            field=models.CharField(max_length=1000, verbose_name='Сорт'),
        ),
    ]
