FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

# Даем права на выполнение entrypoint.sh
COPY entrypoint.dev.sh /entrypoint.dev.sh
RUN chmod +x ./entrypoint.dev.sh
ENTRYPOINT ["./entrypoint.dev.sh"]

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]