version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5

  web:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles  # ✅ Добавлено!
      - ./media:/app/media
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - ./test_templates/assets:/app/assets
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - web
volumes:
  pgdata:
